services:

    #
    # Services
    #
    elcodi.core.currency.service.currency_manager:
        class: %elcodi.core.currency.service.currency_manager.class%
        arguments:
            currency_repository: @elcodi.core.currency.repository.currency
            exchange_rates_repository: @elcodi.core.currency.repository.currency_exchange_rate

    elcodi.currency_manager:
        alias: elcodi.core.currency.service.currency_manager

    elcodi.core.currency.service.exchange_rates_provider:
        class: %elcodi.core.currency.service.exchange_rates_provider.class%

    elcodi.exchange_rates_provider:
        alias: elcodi.core.currency.service.exchange_rates_provider

    elcodi.core.currency.service.cart_session_manager:
        class: %elcodi.core.currency.service.currency_session_manager.class%
        arguments:
            session: @session
            session_field_name: %elcodi.core.currency.session_field_name%

    elcodi.currency_session_manager:
        alias: elcodi.core.currency.service.currency_session_manager

    #
    # Wrappers
    #
    elcodi.core.currency.wrapper.currency:
        class: %elcodi.core.currency.wrapper.currency.class%
        arguments:
            currency_object_manager: @elcodi.repository.currency
            default_currency: %elcodi.core.currency.default_currency%

    elcodi.currency_wrapper:
        alias: elcodi.core.currency.wrapper.currency
